### ISSUE TITLE
Fail to download big zip file from job supervisor

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/cybergis-compute-python-sdk#1]
@zimo-xiao 
There was a big summa job that has a 5.9GB zipped results file. User failed to download it though tried several times.

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-15-13fadee65d0f> in <module>
----> 1 communitySummaJob.download(str(model_folder))
/opt/conda/envs/pysumma/lib/python3.7/site-packages/job_supervisor_client/Job.py in download(self, dir)
     92         dir = self.client.download('GET', '/supervisor/download/' + self.id, {
     93             "aT": self.JAT.getAccessToken()
---> 94         }, dir, self.protocol)
     95         print('file successfully downloaded under: ' + dir)
     96         return dir
/opt/conda/envs/pysumma/lib/python3.7/site-packages/job_supervisor_client/Client.py in download(self, method, uri, body, localDir, protocol)
     33         connection.request(method, uri, json.dumps(body), headers)
     34         response = connection.getresponse()
---> 35         body = response.read()
     36         contentType = response.getheader('Content-Type')
     37 
/opt/conda/envs/pysumma/lib/python3.7/http/client.py in read(self, amt)
    468             else:
    469                 try:
--> 470                     s = self._safe_read(self.length)
    471                 except IncompleteRead:
    472                     self._close_conn()
/opt/conda/envs/pysumma/lib/python3.7/http/client.py in _safe_read(self, amt)
    623             s.append(chunk)
    624             amt -= len(chunk)
--> 625         return b"".join(s)
    626 
    627     def _safe_readinto(self, b):
MemoryError:

**Comment by zimo-xiao** [comment]
The file download is currently using a direct download method which uses a lot of memory. I'll work on it to make the process a stream download.

**Comment by zhiyuli** [comment]
@zimo-xiao  Thanks. This is a high priority issue as far as I can tell. We are using job supervisor to run SUMMA on real-world problems (not toy model anymore), and the downloading of big results is the last missing piece to achieve a fully working workflow.
I am also ccing @padmanabhananand  so he is aware of this.
For long-term, we could look into big file transfer services like Globus.

**Comment by zimo-xiao** [comment]
updated the SDK with streaming download (uses less memory). Please check if this works and close the issue if resolved. @zhiyuli

**Comment by zhiyuli** [comment]
@zimo-xiao 
This new commit still works on small files, but for big files the downloading gets stuck for a long time until a "Kernel Dead" error pops up.
I guest you may need to explicitly enable streaming mode in requests.get(.....,stream=True)?
Can you double check it?

**Comment by zimo-xiao** [comment]
Thanks for the comment. I added the stream option and tested locally. Please try again @zhiyuli

**Comment by alexandermichels** [comment]
@zhiyuli did this ever get sorted out?

**Comment by alexandermichels** [comment]
I believe this refers to v1 download which has been replaced with Globus. I'm going to close, but we can reopen if I misunderstood.
